class PlayingBoard:
  def emotionCoordinates:
    # Randomly generates spawns/coordinates to put the emotion generated by emotion class
  
  def trackScores:
    # Keep track of the score while the player is playing the game (maybe a small screen displays the current score on left/right upper corner)